In [8]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
from LogisticRegression import LogisticRegression as LogisticRegressionBTS
from sklearn.linear_model import LogisticRegression as LogisticRegressionSKL
import CrossValidation as cv
import utils as ut

In [10]:
train_fname = 'train.csv'
test_fname = 'test.csv'

In [27]:
data_train , y_train = ut.extract_features(train_fname)
data_test = ut.extract_features(test_fname, train=True)
#print (len(data_train),len(data_test),y_train)

In [28]:
#train
char_counts = np.array([len(x) for x in data_train])
data_clean_train = ut.clean(data_train)
char_counts_clean = np.array([len(x) for x in data_clean_train])
punct_counts = ut.count_punctuation(data_clean_train)
capital_counts = ut.count_capitals(data_clean_train)[1]

In [29]:
df = pd.DataFrame(dict(label=y_train, char_counts=char_counts, char_counts_clean = char_counts_clean, punct_counts = punct_counts, capital_counts = capital_counts))
df.head(50)
X_train = df.drop('label', axis=1)
X_train

capital_counts  char_counts  char_counts_clean  punct_counts
0           0.245023          682                653      0.059150
1           0.330556          367                360      0.078231
2           0.231214          173                173      0.014286
3           0.282051           39                 39      0.111111
4           0.372881          179                177      0.142857
5           0.346604          426                427      0.044248
6           0.250000          191                192      0.064103
7           0.479167           37                 48      0.027027
8           0.304348           23                 23      0.055556
9           0.257576          132                132      0.089286
10          0.243478          467                460      0.024658
11          0.192982           57                 57      0.020833
12          0.273585          118                106      0.036145
13          0.394737           38                 38      0.096774
14          0.285714           38                 35      0.068966
15          0.240291          412                412      0.035928
16          0.194175          103                103      0.022472
17          0.185366          209                205      0.039548
18          0.217391           46                 46      0.026316
19          0.272321          672                672      0.020484
20          0.267148          277                277      0.057018
21          0.260274           73                 73      0.033898
22          0.272727           88                 88      0.070423
23          0.223140          121                121      0.030303
24          0.223529          254                255      0.009804
25          0.307692           13                 13      0.166667
26          0.247191          264                267      0.036530
27          1.000000           76                 76      0.385714
28          0.235294           17                 17      0.000000
29          0.278351          100                 97      0.025316
...              ...          ...                ...           ...
4385        0.303030           33                 33      0.037037
4386        0.330579          127                121      0.118812
4387        0.248408          157                157      0.053030
4388        0.589744          151                156      0.056452
4389        0.242358          479                458      0.016260
4390        0.276316           76                 76      0.050847
4391        0.222222           27                 27      0.043478
4392        0.215909           88                 88      0.000000
4393        0.255435          184                184      0.034247
4394        0.328125           64                 64      0.075472
4395        0.241176          170                170      0.029412
4396        0.293103          175                174      0.041958
4397        0.242424           33                 33      0.037037
4398        0.730769           76                 78      0.318182
4399        0.214286          266                266      0.036866
4400        0.240580          345                345      0.028571
4401        0.272727           55                 55      0.044444
4402        0.257576           66                 66      0.090909
4403        0.194444           36                 36      0.032258
4404        0.390947          243                243      0.049751
4405        0.235294           34                 34      0.068966
4406        0.367347           49                 49      0.081081
4407        0.200000           40                 40      0.000000
4408        0.284810          207                158      0.023622
4409        0.243386          408                378      0.042623
4410        0.277778           18                 18      0.071429
4411        0.242553          235                235      0.010471
4412        0.377778           44                 45 

In [30]:
#test
char_counts = np.array([len(x) for x in data_test])
data_clean_test = ut.clean(data_test)
char_counts_clean = np.array([len(x) for x in data_clean_test])
punct_counts = ut.count_punctuation(data_clean_test)
capital_counts = ut.count_capitals(data_clean_test)[1]

In [33]:
df_test = pd.DataFrame(dict(char_counts=char_counts, char_counts_clean = char_counts_clean, punct_counts = punct_counts, capital_counts = capital_counts))
df_test.head(50)
X_test = df_test

In [34]:
logBTS = LogisticRegressionBTS(X_train,y_train,tolerance=1e-6)
logBTS.gradient_decent(alpha=1e-3,max_iterations=1e5)
print (logBTS.w.T,logBTS.log_likelihood())

[[  0.4905       0.15078083 -10.2825      -5.1485       0.02159014]] 74548.4949708


In [39]:
score = logBTS.predict_probability(X_train)
result = logBTS.predict(X_train)
result.mean()
diff = abs(result - y_train)
diff.mean()

0.57757644394110985

In [40]:
logreg = LogisticRegressionSKL()
logreg.fit(X_train,y_train)
logreg.score(X_train,y_train)

0.69445073612684027

In [41]:
print (logreg.coef_, logreg.intercept_)

[[ 0.22204892 -0.0083122   0.00766803 -0.50760235]] [-0.73883155]


In [42]:
#y_pred = logreg.predict(X_test)
y_pred = logBTS.predict(X_test)
np.savetxt('y_pred.txt', y_pred, fmt='%s')
y_pred

array([ 1.,  1.,  1., ...,  1.,  1.,  0.])